### ISSUE TITLE
Develop an OpenCV program that processes images from video

### ISSUE THREAD

**Issue by tctrapie** [ncsurobotics/Seawolf-8-Software#25]
What is the task?
Write a opencv program that processes images from video through breaking it down into frames using OpenCV.

Objectives:
First process any video you want.
Finally process the following video added to this issue.

When is this tutorial expected to be completed?
This is not a hard deadline but please try to complete this by the beginning of the spring semester.

Needed Information:
	Video:
https://drive.google.com/file/d/1TWb7wom7rmmZGO-x4LTG2j0uthvsQ2Ut/view?usp=sharing

**Comment by dwhayduk** [comment]
Just uploaded the video2frames_dwhayduk workspace to the computer_vision branch.
