### ISSUE TITLE
Extend Pixhawk unit tests to cover IMU/depth

### ISSUE THREAD

**Issue by akiyeng2** [ncsurobotics/Seawolf-8-Software#8]
For testing IMU/depth: Make up a pose with depth and an orientation in quaternion, then see that `wolf_depth` and `wolf_imu_euler` matches. Quaternions are another way of expressing orientation in space compared to Euler angles (pitch, roll, yaw) that are more robust, but it's simpler to use Euler angles. 

An important note for testing equality of floating points - you don't want to actually see that the two floating point numbers (like pitch, roll, yaw) are completely equal, because they can be off by 1e-10 and the test would fail. Instead, pick some epsilon and check that the result is close enough (1e-5?)

**Comment by Namr** [comment]
I've added simultaneous direction tests. Also not sure what you mean by checking floating point numbers, all the comparison checks in the code are done on integers, though it may be relevant when checking the IMU data.

**Comment by Namr** [comment]
These tests are done, issue can be closed once Pose Control Merges with master
